# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'XCS-Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XCS-Demo
  pod "SimpleLogger", :git => "https://github.com/thinkaboutiter/SimpleLogger.git", :tag => "1.1.3"

  target 'XCS-DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
